export const SET_USER = "SET_USER";
export const LOG_OUT = "LOG_OUT";

//fetch photos
export const SET_PHOTOS = "SET_PHOTOS";
export const DEL_PHOTOS = "DEL_PHOTOS";
export const TOGGLE_PHOTO_FETCHING_STATE = "TOGGLE_PHOTO_FETCHING_STATE";

//fetch public profile
export const PUBLIC_PROFILE = "PUBLIC_PROFILE";
export const TOGGLE_PUBLIC_PROFILE_FETCHING_STATE =
  "TOGGLE_PUBLIC_PROFILE_FETCHING_STATE";

//fetch public user's photos
export const TOGGLE_PUBLIC_PHOTO_FETCHING_STATE =
  "TOGGLE_PUBLIC_PHOTO_FETCHING_STATE";
export const PUBLIC_PHOTO = "PUBLIC_PHOTO";

//fetch public user's liked photos
export const TOGGLE_PUBLIC_USERS_LIKED_PHOTO_FETCHING_STATE =
  "TOGGLE_PUBLIC_USERS_LIKED_PHOTO_FETCHING_STATE";
export const PUBLIC_USERS_LIKED_PHOTOS = "PUBLIC_USERS_LIKED_PHOTOS";

//fetch public user's collection
export const TOGGLE_PUBLIC_USER_COLLECTION_FETCHING_STATE =
  "TOGGLE_PUBLIC_USER_COLLECTION_FETCHING_STATE";
export const PUBLIC_USER_COLLECTION = "PUBLIC_USER_COLLECTION";

//fetch a random photo
export const FETCH_A_RANDOM_PHOTO = "FETCH_A_RANDOM_PHOTO";
export const TOGGLE_RANDOM_PHOTO_FETCHING_STATE =
  "TOGGLE_RANDOM_PHOTO_FETCHING_STATE";

//fetch collection Photos
export const FETCH_COLLECTION_PHOTOS = "FETCH_COLLECTION_PHOTOS";
export const TOGGLE_COLLECTION_PHOTOS_FETCHING_STATE =
  "TOGGLE_COLLECTION_PHOTOS_FETCHING_STATE";

//fetch a single photo by id
export const FETCH_A_PHOTO = "FETCH_A_PHOTO";
export const TOGGLE_SINGLE_PHOTO_FETCHING_STATE =
  "TOGGLE_SINGLE_PHOTO_FETCHING_STATE";

//fetch searched photos
export const SET_SEARCHED_PHOTO = "SET_SEARCHED_PHOTO";
export const TOGGLE_SEARCHED_PHOTO_FETCHING_STATE =
  "TOGGLE_SEARCHED_PHOTO_FETCHING_STATE";

//deleted public user's photo
export const DEL_PUBLIC_PHOTO = "DEL_PUBLIC_PHOTO";
